#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from index.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "index.y"

#include<stdio.h>
int yylex(void);
int yyerror(const char *s);
int flag=1;
extern FILE *yyin;

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IMPORT_KEY	258
#define	STRUCT_KEY	259
#define	VAR_KEY	260
#define	LET_KEY	261
#define	RETURN	262
#define	ELSE	263
#define	USER_DEFINED_FUNCTION_DECLARATION	264
#define	IF	265
#define	BREAK	266
#define	CONTINUE	267
#define	INTEGER_TYPE	268
#define	FLOAT_TYPE	269
#define	DOUBLE_TYPE	270
#define	BOOLEAN_TYPE	271
#define	STRING_TYPE	272
#define	CHARACTER_TYPE	273
#define	VOID_TYPE	274
#define	ARRAY_TYPE	275
#define	DICTIONARY_TYPE	276
#define	LT_CURL_BRACE	277
#define	RT_CURL_BRACE	278
#define	COL_OP	279
#define	STRING_LITERAL	280
#define	CASE	281
#define	CHARACTER_LITERALS	282
#define	IDENTIFIER	283
#define	LT_RND_BRACES	284
#define	SINGLE_LINE_COMMENT	285
#define	MULTI_LINE_COMMENT	286
#define	EQUAL	287
#define	RT_RND_BRACES	288
#define	EQUALEQUAL	289
#define	NOEQUAL	290
#define	GREATEREQUAL	291
#define	LESSEQUAL	292
#define	GREATER	293
#define	LESSER	294
#define	MODULOEQUAL	295
#define	MINUSEQUAL	296
#define	WHILE_KEY	297
#define	PLUSEQUAL	298
#define	MULTIEQUAL	299
#define	DIVEQUAL	300
#define	DIVISION	301
#define	MODULO	302
#define	PLUS	303
#define	MINUS	304
#define	MULTIPLY	305
#define	NOT_OPERATOR	306
#define	AND_OPERATOR	307
#define	OR_OPERATOR	308
#define	IN_KEY	309
#define	XOR_OPERATOR	310
#define	LEFT_SHIFT_EQUAL	311
#define	RIGHT_SHIFT_EQUAL	312
#define	SWITCH	313
#define	DEFAULT	314
#define	FOR_KEY	315


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IMPORT_KEY;
static const int STRUCT_KEY;
static const int VAR_KEY;
static const int LET_KEY;
static const int RETURN;
static const int ELSE;
static const int USER_DEFINED_FUNCTION_DECLARATION;
static const int IF;
static const int BREAK;
static const int CONTINUE;
static const int INTEGER_TYPE;
static const int FLOAT_TYPE;
static const int DOUBLE_TYPE;
static const int BOOLEAN_TYPE;
static const int STRING_TYPE;
static const int CHARACTER_TYPE;
static const int VOID_TYPE;
static const int ARRAY_TYPE;
static const int DICTIONARY_TYPE;
static const int LT_CURL_BRACE;
static const int RT_CURL_BRACE;
static const int COL_OP;
static const int STRING_LITERAL;
static const int CASE;
static const int CHARACTER_LITERALS;
static const int IDENTIFIER;
static const int LT_RND_BRACES;
static const int SINGLE_LINE_COMMENT;
static const int MULTI_LINE_COMMENT;
static const int EQUAL;
static const int RT_RND_BRACES;
static const int EQUALEQUAL;
static const int NOEQUAL;
static const int GREATEREQUAL;
static const int LESSEQUAL;
static const int GREATER;
static const int LESSER;
static const int MODULOEQUAL;
static const int MINUSEQUAL;
static const int WHILE_KEY;
static const int PLUSEQUAL;
static const int MULTIEQUAL;
static const int DIVEQUAL;
static const int DIVISION;
static const int MODULO;
static const int PLUS;
static const int MINUS;
static const int MULTIPLY;
static const int NOT_OPERATOR;
static const int AND_OPERATOR;
static const int OR_OPERATOR;
static const int IN_KEY;
static const int XOR_OPERATOR;
static const int LEFT_SHIFT_EQUAL;
static const int RIGHT_SHIFT_EQUAL;
static const int SWITCH;
static const int DEFAULT;
static const int FOR_KEY;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IMPORT_KEY=258
	,STRUCT_KEY=259
	,VAR_KEY=260
	,LET_KEY=261
	,RETURN=262
	,ELSE=263
	,USER_DEFINED_FUNCTION_DECLARATION=264
	,IF=265
	,BREAK=266
	,CONTINUE=267
	,INTEGER_TYPE=268
	,FLOAT_TYPE=269
	,DOUBLE_TYPE=270
	,BOOLEAN_TYPE=271
	,STRING_TYPE=272
	,CHARACTER_TYPE=273
	,VOID_TYPE=274
	,ARRAY_TYPE=275
	,DICTIONARY_TYPE=276
	,LT_CURL_BRACE=277
	,RT_CURL_BRACE=278
	,COL_OP=279
	,STRING_LITERAL=280
	,CASE=281
	,CHARACTER_LITERALS=282
	,IDENTIFIER=283
	,LT_RND_BRACES=284
	,SINGLE_LINE_COMMENT=285
	,MULTI_LINE_COMMENT=286
	,EQUAL=287
	,RT_RND_BRACES=288
	,EQUALEQUAL=289
	,NOEQUAL=290
	,GREATEREQUAL=291
	,LESSEQUAL=292
	,GREATER=293
	,LESSER=294
	,MODULOEQUAL=295
	,MINUSEQUAL=296
	,WHILE_KEY=297
	,PLUSEQUAL=298
	,MULTIEQUAL=299
	,DIVEQUAL=300
	,DIVISION=301
	,MODULO=302
	,PLUS=303
	,MINUS=304
	,MULTIPLY=305
	,NOT_OPERATOR=306
	,AND_OPERATOR=307
	,OR_OPERATOR=308
	,IN_KEY=309
	,XOR_OPERATOR=310
	,LEFT_SHIFT_EQUAL=311
	,RIGHT_SHIFT_EQUAL=312
	,SWITCH=313
	,DEFAULT=314
	,FOR_KEY=315


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IMPORT_KEY=258;
const int YY_parse_CLASS::STRUCT_KEY=259;
const int YY_parse_CLASS::VAR_KEY=260;
const int YY_parse_CLASS::LET_KEY=261;
const int YY_parse_CLASS::RETURN=262;
const int YY_parse_CLASS::ELSE=263;
const int YY_parse_CLASS::USER_DEFINED_FUNCTION_DECLARATION=264;
const int YY_parse_CLASS::IF=265;
const int YY_parse_CLASS::BREAK=266;
const int YY_parse_CLASS::CONTINUE=267;
const int YY_parse_CLASS::INTEGER_TYPE=268;
const int YY_parse_CLASS::FLOAT_TYPE=269;
const int YY_parse_CLASS::DOUBLE_TYPE=270;
const int YY_parse_CLASS::BOOLEAN_TYPE=271;
const int YY_parse_CLASS::STRING_TYPE=272;
const int YY_parse_CLASS::CHARACTER_TYPE=273;
const int YY_parse_CLASS::VOID_TYPE=274;
const int YY_parse_CLASS::ARRAY_TYPE=275;
const int YY_parse_CLASS::DICTIONARY_TYPE=276;
const int YY_parse_CLASS::LT_CURL_BRACE=277;
const int YY_parse_CLASS::RT_CURL_BRACE=278;
const int YY_parse_CLASS::COL_OP=279;
const int YY_parse_CLASS::STRING_LITERAL=280;
const int YY_parse_CLASS::CASE=281;
const int YY_parse_CLASS::CHARACTER_LITERALS=282;
const int YY_parse_CLASS::IDENTIFIER=283;
const int YY_parse_CLASS::LT_RND_BRACES=284;
const int YY_parse_CLASS::SINGLE_LINE_COMMENT=285;
const int YY_parse_CLASS::MULTI_LINE_COMMENT=286;
const int YY_parse_CLASS::EQUAL=287;
const int YY_parse_CLASS::RT_RND_BRACES=288;
const int YY_parse_CLASS::EQUALEQUAL=289;
const int YY_parse_CLASS::NOEQUAL=290;
const int YY_parse_CLASS::GREATEREQUAL=291;
const int YY_parse_CLASS::LESSEQUAL=292;
const int YY_parse_CLASS::GREATER=293;
const int YY_parse_CLASS::LESSER=294;
const int YY_parse_CLASS::MODULOEQUAL=295;
const int YY_parse_CLASS::MINUSEQUAL=296;
const int YY_parse_CLASS::WHILE_KEY=297;
const int YY_parse_CLASS::PLUSEQUAL=298;
const int YY_parse_CLASS::MULTIEQUAL=299;
const int YY_parse_CLASS::DIVEQUAL=300;
const int YY_parse_CLASS::DIVISION=301;
const int YY_parse_CLASS::MODULO=302;
const int YY_parse_CLASS::PLUS=303;
const int YY_parse_CLASS::MINUS=304;
const int YY_parse_CLASS::MULTIPLY=305;
const int YY_parse_CLASS::NOT_OPERATOR=306;
const int YY_parse_CLASS::AND_OPERATOR=307;
const int YY_parse_CLASS::OR_OPERATOR=308;
const int YY_parse_CLASS::IN_KEY=309;
const int YY_parse_CLASS::XOR_OPERATOR=310;
const int YY_parse_CLASS::LEFT_SHIFT_EQUAL=311;
const int YY_parse_CLASS::RIGHT_SHIFT_EQUAL=312;
const int YY_parse_CLASS::SWITCH=313;
const int YY_parse_CLASS::DEFAULT=314;
const int YY_parse_CLASS::FOR_KEY=315;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		150
#define	YYFLAG		-32768
#define	YYNTBASE	61

#define YYTRANSLATE(x) ((unsigned)(x) <= 315 ? yytranslate[x] : 99)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,     9,    11,    14,    17,    19,    21,    23,
    25,    27,    31,    35,    37,    39,    41,    44,    46,    48,
    55,    59,    61,    63,    65,    67,    69,    71,    73,    75,
    77,    81,    84,    86,    88,    90,    92,    94,    96,    98,
   100,   102,   104,   106,   109,   111,   113,   119,   123,   127,
   129,   131,   133,   135,   140,   143,   145,   147,   149,   151,
   153,   157,   160,   164,   166,   170,   174,   176,   178,   181,
   183,   185,   187,   189,   191,   193,   195,   197,   199,   201,
   203,   205,   207,   209,   211,   213,   215,   217,   219,   221,
   223,   225,   227,   231,   235,   238,   240,   245,   249,   251,
   253
};

static const short yyrhs[] = {    62,
    64,     0,    63,    62,     0,    84,    62,     0,    98,     0,
     3,    25,     0,    64,    65,     0,    65,     0,    77,     0,
    71,     0,    66,     0,    84,     0,     4,    28,    67,     0,
    22,    68,    23,     0,    69,     0,    71,     0,    66,     0,
    70,    28,     0,     5,     0,     6,     0,     9,    28,    29,
    72,    33,    74,     0,    28,    24,    73,     0,    13,     0,
    14,     0,    15,     0,    16,     0,    17,     0,    18,     0,
    19,     0,    20,     0,    21,     0,    22,    75,    23,     0,
    75,    76,     0,    76,     0,    85,     0,    88,     0,    81,
     0,    78,     0,    84,     0,    86,     0,    77,     0,    71,
     0,    82,     0,    83,     0,    70,    28,     0,    79,     0,
    80,     0,    60,    28,    54,    87,    74,     0,    42,    90,
    74,     0,    28,    29,    33,     0,    11,     0,    12,     0,
    30,     0,    31,     0,    70,    28,    32,    97,     0,     7,
    87,     0,    28,     0,    97,     0,    98,     0,    89,     0,
    93,     0,    10,    90,    74,     0,    89,    89,     0,    89,
     8,    74,     0,    91,     0,    91,    92,    91,     0,    29,
    91,    33,     0,    28,     0,    97,     0,    92,    28,     0,
    32,     0,    34,     0,    35,     0,    36,     0,    37,     0,
    38,     0,    39,     0,    40,     0,    41,     0,    43,     0,
    44,     0,    45,     0,    46,     0,    47,     0,    48,     0,
    49,     0,    50,     0,    51,     0,    52,     0,    53,     0,
    55,     0,    56,     0,    57,     0,    58,    28,    94,     0,
    22,    95,    23,     0,    95,    96,     0,    96,     0,    26,
    97,    24,    75,     0,    59,    24,    75,     0,    25,     0,
    27,     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    20,    23,    24,    25,    28,    31,    32,    35,    36,    36,
    36,    38,    40,    42,    42,    42,    44,    46,    46,    48,
    50,    52,    52,    52,    52,    52,    52,    52,    52,    52,
    54,    56,    56,    58,    58,    58,    58,    58,    58,    58,
    58,    58,    58,    60,    62,    62,    64,    66,    68,    70,
    72,    74,    74,    76,    79,    81,    81,    81,    83,    83,
    85,    85,    85,    87,    89,    89,    89,    89,    89,    91,
    91,    91,    91,    91,    91,    91,    91,    91,    91,    91,
    91,    91,    91,    91,    91,    91,    91,    91,    91,    91,
    91,    91,    93,    96,    99,   100,   103,   104,   107,   107,
   109
};

static const char * const yytname[] = {   "$","error","$illegal.","IMPORT_KEY",
"STRUCT_KEY","VAR_KEY","LET_KEY","RETURN","ELSE","USER_DEFINED_FUNCTION_DECLARATION",
"IF","BREAK","CONTINUE","INTEGER_TYPE","FLOAT_TYPE","DOUBLE_TYPE","BOOLEAN_TYPE",
"STRING_TYPE","CHARACTER_TYPE","VOID_TYPE","ARRAY_TYPE","DICTIONARY_TYPE","LT_CURL_BRACE",
"RT_CURL_BRACE","COL_OP","STRING_LITERAL","CASE","CHARACTER_LITERALS","IDENTIFIER",
"LT_RND_BRACES","SINGLE_LINE_COMMENT","MULTI_LINE_COMMENT","EQUAL","RT_RND_BRACES",
"EQUALEQUAL","NOEQUAL","GREATEREQUAL","LESSEQUAL","GREATER","LESSER","MODULOEQUAL",
"MINUSEQUAL","WHILE_KEY","PLUSEQUAL","MULTIEQUAL","DIVEQUAL","DIVISION","MODULO",
"PLUS","MINUS","MULTIPLY","NOT_OPERATOR","AND_OPERATOR","OR_OPERATOR","IN_KEY",
"XOR_OPERATOR","LEFT_SHIFT_EQUAL","RIGHT_SHIFT_EQUAL","SWITCH","DEFAULT","FOR_KEY",
"program","headers","imports","declaration_list","declaration","struct_declaration",
"structblock","struct_memebers","keywords_declaration","keywords_type","function_declaration",
"typecasting_params","datatypes","block","statements","statement","variable_declaration",
"iterative","forloops","whileloops","function_call","break","continue","comment",
"assignment","return","identifier","conditional","if_statement","condition",
"expression","operator","switchstatement","switchblock","caselist","case","literals",
"empty",""
};
#endif

static const short yyr1[] = {     0,
    61,    62,    62,    62,    63,    64,    64,    65,    65,    65,
    65,    66,    67,    68,    68,    68,    69,    70,    70,    71,
    72,    73,    73,    73,    73,    73,    73,    73,    73,    73,
    74,    75,    75,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    77,    78,    78,    79,    80,    81,    82,
    83,    84,    84,    85,    86,    87,    87,    87,    88,    88,
    89,    89,    89,    90,    91,    91,    91,    91,    91,    92,
    92,    92,    92,    92,    92,    92,    92,    92,    92,    92,
    92,    92,    92,    92,    92,    92,    92,    92,    92,    92,
    92,    92,    93,    94,    95,    95,    96,    96,    97,    97,
    98
};

static const short yyr2[] = {     0,
     2,     2,     2,     1,     2,     2,     1,     1,     1,     1,
     1,     3,     3,     1,     1,     1,     2,     1,     1,     6,
     3,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     3,     2,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     2,     1,     1,     5,     3,     3,     1,
     1,     1,     1,     4,     2,     1,     1,     1,     1,     1,
     3,     2,     3,     1,     3,     3,     1,     1,     2,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     3,     3,     2,     1,     4,     3,     1,     1,
     0
};

static const short yydefact[] = {   101,
     0,    52,    53,     0,   101,   101,     4,     5,     0,    18,
    19,     0,     1,     7,    10,     0,     9,     8,    11,     2,
     3,     0,     0,     6,    44,     0,    12,     0,    16,     0,
    14,     0,    15,     0,     0,    13,    17,     0,     0,    22,
    23,    24,    25,    26,    27,    28,    29,    30,    21,     0,
    20,   101,     0,    50,    51,     0,     0,     0,     0,     0,
    41,     0,    33,    40,    37,    45,    46,    36,    42,    43,
    38,    34,    39,    35,    59,    60,    99,   100,    56,    55,
    57,    58,    67,     0,    70,    71,    72,    73,    74,    75,
    76,    77,    78,    79,    80,    81,    82,    83,    84,    85,
    86,    87,    88,    89,    90,    91,    92,     0,    64,     0,
    68,     0,     0,     0,     0,    44,    31,    32,     0,    62,
     0,    61,     0,    69,    49,    48,     0,    93,   101,     0,
    63,    66,    65,     0,     0,     0,    96,     0,    54,     0,
     0,    94,    95,    47,     0,    98,    97,     0,     0,     0
};

static const short yydefgoto[] = {   148,
     4,     5,    13,    14,    15,    27,    30,    31,    60,    61,
    35,    49,    51,    62,    63,    64,    65,    66,    67,    68,
    69,    70,    71,    72,    73,    80,    74,    75,   108,   109,
   110,    76,   128,   136,   137,   111,     7
};

static const short yypact[] = {    22,
     3,-32768,-32768,   115,    22,    22,-32768,-32768,     6,-32768,
-32768,    11,   115,-32768,-32768,    14,-32768,-32768,-32768,-32768,
-32768,    28,    37,-32768,-32768,   130,-32768,    33,-32768,    49,
-32768,    47,-32768,    63,    58,-32768,-32768,   112,    81,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,     7,
-32768,    46,    61,-32768,-32768,    86,    61,    94,    95,   109,
-32768,    -1,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,    52,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,    61,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    81,   142,   110,
-32768,   107,    81,   119,    88,   111,-32768,-32768,    81,    52,
   116,-32768,    61,-32768,-32768,-32768,   -11,-32768,    46,    67,
-32768,-32768,   142,    67,   120,    -3,-32768,    81,-32768,   123,
     7,-32768,-32768,-32768,     7,     7,     7,   158,   170,-32768
};

static const short yypgoto[] = {-32768,
    76,-32768,-32768,   162,   174,-32768,-32768,-32768,    32,    50,
-32768,-32768,   -87,  -101,   -62,    20,-32768,-32768,-32768,-32768,
-32768,-32768,    64,-32768,-32768,    55,-32768,   -73,   139,   -77,
   -78,-32768,-32768,-32768,    65,   -51,   -49
};


#define	YYLAST		201


static const short yytable[] = {   118,
    81,   120,    82,    10,    11,    52,   121,    12,    53,    54,
    55,    10,    11,    52,   134,    12,    53,    54,    55,   142,
   122,   117,   134,    18,     1,   126,    56,     8,     2,     3,
   123,   131,    18,    22,    56,    16,     2,     3,    23,   146,
    57,    25,   123,   147,    16,   133,   120,   135,    57,    26,
   144,     2,     3,    17,   123,   135,    58,    32,    59,   119,
    34,    53,    17,     6,    58,    28,    59,    19,     6,     6,
    77,    36,    78,    79,    37,    33,    19,    81,   139,    82,
    20,    21,   140,   118,   118,    77,    38,    78,    83,    84,
    39,    77,    85,    78,    86,    87,    88,    89,    90,    91,
    92,    93,    50,    94,    95,    96,    97,    98,    99,   100,
   101,   102,   103,   104,   112,   105,   106,   107,     9,    10,
    11,   114,   115,    12,    40,    41,    42,    43,    44,    45,
    46,    47,    48,     9,    10,    11,   116,   124,    12,   125,
   127,   129,   130,   141,     2,     3,   145,    85,   132,    86,
    87,    88,    89,    90,    91,    92,    93,   149,    94,    95,
    96,    97,    98,    99,   100,   101,   102,   103,   104,   150,
   105,   106,   107,    85,    24,    86,    87,    88,    89,    90,
    91,    92,    93,   138,    94,    95,    96,    97,    98,    99,
   100,   101,   102,   103,   104,   113,   105,   106,   107,    29,
   143
};

static const short yycheck[] = {    62,
    52,    75,    52,     5,     6,     7,    84,     9,    10,    11,
    12,     5,     6,     7,    26,     9,    10,    11,    12,    23,
   108,    23,    26,     4,     3,   113,    28,    25,    30,    31,
   109,   119,    13,    28,    28,     4,    30,    31,    28,   141,
    42,    28,   121,   145,    13,   123,   120,    59,    42,    22,
   138,    30,    31,     4,   133,    59,    58,    26,    60,     8,
    28,    10,    13,     0,    58,    29,    60,     4,     5,     6,
    25,    23,    27,    28,    28,    26,    13,   129,   130,   129,
     5,     6,   134,   146,   147,    25,    24,    27,    28,    29,
    33,    25,    32,    27,    34,    35,    36,    37,    38,    39,
    40,    41,    22,    43,    44,    45,    46,    47,    48,    49,
    50,    51,    52,    53,    29,    55,    56,    57,     4,     5,
     6,    28,    28,     9,    13,    14,    15,    16,    17,    18,
    19,    20,    21,     4,     5,     6,    28,    28,     9,    33,
    22,    54,    32,    24,    30,    31,    24,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    41,     0,    43,    44,
    45,    46,    47,    48,    49,    50,    51,    52,    53,     0,
    55,    56,    57,    32,    13,    34,    35,    36,    37,    38,
    39,    40,    41,   129,    43,    44,    45,    46,    47,    48,
    49,    50,    51,    52,    53,    57,    55,    56,    57,    26,
   136
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 110 "index.y"


void main() 
{ 
  FILE *fo;
  fo=fopen("input.txt","r");
  yyin=fo;
  //printf("\nEnter:\n"); 
  yyparse(); 
  if(flag) 
  	printf("\nValid\n"); 
}   
int yyerror(const char *msg) 
{ 
   extern int yylineno;
   printf("\nInvalid\n LN: %d %s\n",yylineno,msg); 
   flag=0;
   return 0; 
} 